from linked_list.OneWayLinkedList import OneWayLinkedList
from linked_list.TwoWayLinkedList import TwoWayLinkedList
from linked_list.circulate import CirculateLinkedList

singly_linkedList = OneWayLinkedList
doubly_linkedList = TwoWayLinkedList
circulate_linkedList = CirculateLinkedList
